### PR TITLE
Fix release downloads by using GitHub API rather than browser URL

### PR DESCRIPTION
**Pull request by erichoracek**
Currently, Carthage uses the `browser_url` field on a GitHub release asset to download precompiled binaries. However, when downloading a private binary, this URL only succeeds if the user is logged into their GitHub account on Safari. This is because the cookies are shared between Safari and Carthage, and thus the browser URL request is successful because the user is already authenticated. As such, If the user is **not** logged into their GitHub account in Safari, the download fails with an opaque error stating that the release zip file is invalid. When you inspect the contents of the downloaded file in the `~/Libarary/Caches/org.carthage.CarthageKit/binaries/` directory, the contents of the file are the string "Not Found", rather than the zipped `.framework` that you'd expect.

To rememdy this, we use the GitHub release asset API with a content type of `application/octet-stream` to download the asset, as described [here](https://developer.github.com/v3/repos/releases/#get-a-single-release-asset). This ensures that private release assets are downloaded successfully regardless of whether the user is logged into Safari.

### CODE REVIEW

**Comment by robrix** [comment]
Hah. Good fix :+1:

**Comment by robrix** [comment]
Also: good diagnosis! That sounds like it mustn’t have been fun :grimacing:

**Comment by robrix** [comment]
Short & sweet PR :+1:

**Comment by mdiep** [comment]
Thank you for opening a PR for this! :sparkles:

**Pull request merged**
