### PR TITLE
Suppress NosharedFrameworkSchemes error in order to continue building dependencies

### PR DESCRIPTION
**Pull request by yasuoza**
Version 0.8 introduced `.NosharedFrameworkSchemes` error to skip building dependencies which has no scheme at all.

This was OK for normal build/update command, but with `platform` argument, this make carthage stop building when a dependency has no scheme for the given platform.

To solve above issue, just suppress `.NosharedFrameworkSchemes` error while building dependencies and let carthage continue building project's dependencies.

With this PR, carthage behavior will be same as 0.6 ~ 0.7.x.

---

Steps to reproduce the issue.

Cartfile:

```
github "Alamofire/Alamofire"
github "SwiftyJSON/SwiftyJSON"
github "TransitApp/SVProgressHUD"
```

```bash
$ carthage update --platform macosx
*** Fetching SVProgressHUD
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out SwiftyJSON at "2.2.1"
*** Checking out SVProgressHUD at "1.1.3"
*** Checking out Alamofire at "1.3.1"
*** xcodebuild output can be found in /var/folders/cg/v15m2zq94p3czs9kltkbngmm0000gn/T/carthage-xcodebuild.DqrfOr.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
Dependency "SVProgressHUD" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/TransitApp/SVProgressHUD/issues/new
```

With this PR,

```bash
$ carthage update --platform macosx
*** Fetching SVProgressHUD
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out SVProgressHUD at "1.1.3"
*** Checking out SwiftyJSON at "2.2.1"
*** Checking out Alamofire at "1.3.1"
*** xcodebuild output can be found in /var/folders/cg/v15m2zq94p3czs9kltkbngmm0000gn/T/carthage-xcodebuild.MDwKTH.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "SwiftyJSON OSX" in SwiftyJSON.xcworkspace
```

### CODE REVIEW

**Comment by ikesyo** [comment]
Thank you for the pull request! However, why are you adding a dependency which only supports iOS, to the project which targets OS X?

The changes of this PR breaks the functionality `.NosharedFrameworkSchemes` would provide (it now only works for `carthage build --no-skip-current` if the current project itself has no shared framework schemes).

**Comment by yasuoza** [comment]
> However, why are you adding a dependency which only supports iOS, to the project which targets OS X?

That was a sample code. I want to have dependencies some for only iOS and some for only watchOS. 
So I want to use `platform` argument to minimize building/updating dependencies.

> The changes of this PR breaks the functionality

Does 'functionality' means making a error and stop building or print 'No shared framework'?

**Comment by ikesyo** [comment]
> Does 'functionality' means making a error and stop building or print 'No shared framework'?

Yes, `github "hubertr/Swell" == 0.5.0` and `carthage update` with Carthage 0.8 would have the following result:

```bash
*** Fetching Swell
*** Checking out Swell at "0.5.0"
*** xcodebuild output can be found in /var/folders/ch/frqqndbn45l5dxldwqprh0jr0000gn/T/carthage-xcodebuild.ADF7v6.log
Dependency "Swell" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/hubertr/Swell/issues/new
```

but with the modified version, that doesn't print any error, it isn't an intended behavior.

**Comment by yasuoza** [comment]
>  that doesn't print any error

Yes, I tried to print some _warnings_ and keep carthage building another dependencies but I couldn't find how to do it.
Is there any way to pass a _message_ from CarthageKit to carthage?

**Comment by ikesyo** [comment]
> Is there any way to pass a message from CarthageKit to carthage?

IMO there is no instant way of doing that. I'd like to find another option to address the issue you described above, perhaps in another pull request.

**Comment by yasuoza** [comment]
>  I'd like to find another option to address the issue

I'm looking forward to seeing it.Thank you.

**Comment by ikesyo** [comment]
@yasuoza I created a new PR #679, could you please check the branch if it work as you expect?

**Comment by yasuoza** [comment]
Closes in favor of #679

**Pull request closed without merging**
