### PR TITLE
Lenient framework platform check. 

### PR DESCRIPTION
**Pull request by blender**
If platform can't be determined, report error and don't fail entire chain.

See https://github.com/Carthage/Carthage/issues/2430#issuecomment-383837595 

Note: I would like to rebase in one commit before anyone merges

### CODE REVIEW

**Comment by mdiep** [comment]
I think failing the whole build is actually the right thing to do here. 😕 It ensures that (1) framework authors fix up issues and (2) framework consumers don't miss it if the framework isn't valid.

**Comment by blender** [comment]
Good points @mdiep . 

However I think that then [this check](https://github.com/Carthage/Carthage/blob/b18a85dfefe4e1a640453a6721807e8b9d751b4a/Source/CarthageKit/Project.swift#L1281) is a little too loose. That function is only used when deciding what `.frameworks` to copy.

I could rework it to check if there is binary, and if the binary is a dynamic (and soon static) framework. Filter out false positives otherwise.

The fact that Carthage doesn't enforce a specific shape (i.e. directory structure) for the downloaded archive is very powerful because any archive goes. The motivation for the current change is that directories that are named `.framework` currently are picked up here and it's a bit of shame that the [archive Fabric provides (see comment(https://github.com/Carthage/Carthage/issues/2430#issuecomment-383837595))] fails because it contains a bogus directory called`Fabric.framework` containing a shell script.

I though that since Google, despite it's size,  [doesn't  want to play ball](https://github.com/firebase/firebase-ios-sdk/issues/9#issuecomment-381746071) I'd skip invalid archives instead of filtering them out silently as I suggested above. Or maybe, I should filter them out and just log that they are being ignored. 

I think that, whatever implementation is chosen in the end if any at all, this is a change for good for the following reasons:

- Naming a bundle `.framework` doesn't make it a framework (mistake in Carthage's logic here) and bogus bundles should be ignored.
- Increase the end user's security by making it possible to use and archive provided by Goolge instead of an archive [hosted by 3rd parties](https://github.com/Carthage/Carthage/issues/2036#issue-239346388)

**Comment by mdiep** [comment]
I think I like this alternative approach. It seems simpler.

But we should make sure that we reuse/share any logic there if possible. There's an existing `PackageType` that might be of use, e.g.

**Comment by blender** [comment]
@mdiep PackageType is in Carthage, while this logic is in CarthageKit. I can move it ofc.

**Comment by blender** [comment]
Closing. Superseded by #2436

**Pull request closed without merging**
