### PR TITLE
Update Commandant

### PR DESCRIPTION
**Pull request by mdiep**
This updates Carthage to use the changes proposed in https://github.com/Carthage/Commandant/pull/41.

### CODE REVIEW

**Comment by mdiep** [comment]
This PR now includes all the changes for Commandant 0.8.

Ready for review!

**Comment by mdiep** [comment]
Also, the diff is much easier to read if you [ignore whitespace](https://github.com/Carthage/Carthage/pull/987/files?w=1).

**Comment by NachoSoto** [comment]
Looks good :shipit:

**Comment by ikesyo** [comment]
Seems good too! :+1:

**Pull request merged**
