### PR TITLE
Fetch GitHub Releases by specific tag

### PR DESCRIPTION
**Pull request by jspahrsummers**
Much better than enumerating all of them!

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Oops, need to fix the handling of tags without any releases.

**Comment by jspahrsummers** [comment]
Nevermind! Nothing to do, because it just gives us a Release without any assets. :sparkles:

**Comment by pengwynn** [comment]
:tada:

**Comment by jspahrsummers** [comment]
Tests pass locally, so I'm just gonna merge and chalk it up to Travis oddities.

**Pull request merged**
