### PR TITLE
Remove the section on copying dSYM files

### LINKED ISSUE #918: Is the section on Copying dSYMs required anymore / outdated?
Following #853 Do the dysms need to be manually copied over anymore?

### PR DESCRIPTION
**Pull request by Abizern**
Closes #918

### CODE REVIEW

**Comment by mdiep** [comment]
I think this should still be suggested for OS X builds, which don't require the use of `copy-frameworks`?

**Comment by furyu-ikeda-sho** [comment]
> for OS X builds, which don't require the use of `copy-frameworks`?

That'a good point, and since the `copy-frameworks` doesn't copy dSYM files automatically as noted in #918, this is still required for iOS builds too.

**Comment by ikesyo** [comment]
> for OS X builds, which don't require the use of `copy-frameworks`?

That'a good point, and since the `copy-frameworks` doesn't copy dSYM files automatically as noted in #918, this is still required for iOS builds too.

**Comment by ikesyo** [comment]
Closing this, thank you for the PR though!

**Comment by Abizern** [comment]
NP. That's the way this is supposed to work.

**Pull request closed without merging**
