### PR TITLE
Set ONLY_ACTIVE_ARCH=NO when building

### LINKED ISSUE #504: Force ONLY_ACTIVE_ARCH=NO when building
Most Debug builds set `ONLY_ACTIVE_ARCH=YES`, which is currently honored when you run `carthage build --configuration Debug`.

Unfortunately, this can cause problems for iOS targets, because it means that you may not be able to actually run your build on the device you have connected to your machine (for example, if the active arch is `arm64` but you're trying to run on a 32-bit device).

Since part of the appeal of Carthage is that it gives you frameworks which mostly “just work,” I think we should build for all valid architectures regardless of the chosen build configuration.

### PR DESCRIPTION
**Pull request by ikesyo**
Resolves #504.

~~This currently sets the flag for all `xcodebuild` tasks other than `xcodebuild build`.~~

### CODE REVIEW

**Comment by jspahrsummers** [comment]
> This currently sets the flag for all `xcodebuild` tasks other than `xcodebuild build`.

This seems backwards. Shouldn't it _only_ set the flag for `xcodebuild build`?

**Comment by ikesyo** [comment]
I limited setting the flag only when building (when `sdk` is specified). Or should we add another property to `BuildArguments`?

**Comment by jspahrsummers** [comment]
It does seem like another property in `BuildArguments` would make sense. We don't want to pass `ONLY_ACTIVE_ARCH` when we're trying to read a project's build settings, for example.

**Comment by ikesyo** [comment]
@jspahrsummers Thanks for the feedback! I've addressed the points. :boom:

**Comment by mdiep** [comment]
This looks fine to me.

@jspahrsummers, do you want to take another look?

**Comment by jspahrsummers** [comment]
:+1: Sorry for the delay!

**Pull request merged**
