### PR TITLE
Locate schemes concurrently

### PR DESCRIPTION
**Pull request by elliottwilliams**
In large repos (repos with many xcode projects in them, or repos with deeply nested directories), `buildableSchemesInDirectory` can become noticeably slow.

This change makes the directory enumerator stop descending when we filter out a URL, and calls `xcodebuild -list` concurrently using the same pattern that Carthage uses further down.

### CODE REVIEW

**Comment by elliottwilliams** [comment]
@tmspzz take a look if you've still got bandwidth. FWIW, my team has been using this in production for a couple months w/o issues.

**Comment by tmspzz** [comment]
LGTM

**Review by tmspzz — APPROVED** [review]

**Review by Devkey19 — COMMENTED** [review]
Thanks

**Review by Devkey19 — COMMENTED** [review]
Thanks

**Pull request merged**
