### PR TITLE
[WIP] Add `carthage cleanup` command

### PR DESCRIPTION
**Pull request by chuganzy**
Add `carthage cleanup` command.
Summary is [here](https://github.com/Carthage/Carthage/pull/2333#issuecomment-369927726).

Addresses https://github.com/Carthage/Carthage/issues/902.

## TODOs
- [x] Error handling
- [x] Logging
- [x] Test

### CODE REVIEW

**Comment by blender** [comment]
@chuganzy ping

**Comment by chuganzy** [comment]
@blender Sorry I was busy these days. I'll keep working on this this weekend!

**Comment by blender** [comment]
@chuganzy nice progress you have made.

I have read the linked issue but I'm not sure I follow your implementation.

This adds a new cleanup command that deletes:

- Binaries
- dSYMs
- version files

however it seems to leave bcsymbolmaps? 

Also this seems to halt on the first version file missing. 

Can you go in a little more detail about your implementation?

**Comment by chuganzy** [comment]
This command deletes:
* Binaries
* dSYMs
* version files
which are no longer needed.

I thought all of bcsymbolmaps are not actually used but apparently they are needed to upload the app to iTunes Connect.. I'll figure out how to clear bcsymbolmaps which is no longer used..

**Comment by blender** [comment]
the bcsymbolmaps can be derived from the dsyms or form the framework binaries. There should be code for that.

However I must ask, why would one use this command and not just delete the Carthage/Build folder?

**Comment by chuganzy** [comment]
On CI we cache Carthage directory and run `carthage bootstrap --use-cache` every time. The problem is that carthage keeps old files which are no longer used, so Carthage directory is getting bigger.. Also I want to keep build cache as far as possible.

**Comment by blender** [comment]
So if I understand correctly this would make sure that the artifacts in the build folder are only the ones that should produces according to the current Cartfile.resolved?

**Comment by chuganzy** [comment]
Exactly

**Comment by blender** [comment]
@chuganzy I'm good with that even if it sounds a little more of a workflow problem than a Carthage problem. Should this apply to the checkout folder too?

I think we go the discussion at a good point here and I'm going to summarize for @mdiep:

### Goal
Carthage should be able to clean after itself.

### Motivation
When changing dependencies, a lot of artifacts from non-relevant dependencies are left behind cluttering the `Carthage/Build` folder. This can be solved by removing the `Carthage/Build` folder but this would discard relevant artifacts as well. A smart clean-up is required.

### Current limitations
No limitations

### Proposed solution
Add a cleanup command to make sure that the artifacts in the build folder are only the ones that would be produced according to the current Cartfile.resolved.

**Comment by mdiep** [comment]
I'm good with this if we can correctly figure out which things are no longer needed. 👍

**Comment by blender** [comment]
We are able to figure out the complementary set of things (what to keep) so we should be good.

**Comment by chuganzy** [comment]
Thanks @blender for summarizing!

**Comment by blender** [comment]
@chuganzy I think the cleanup should apply to everything, including the checkouts.

**Comment by blender** [comment]
@chuganzy  ping

**Comment by chuganzy** [comment]
Sorry I could not work on this for a while.. Currently it clears all the `bcsymbolmap` but I'm going to refactor the part. Please hold on!

**Comment by blender** [comment]
ping

**Comment by blender** [comment]
@chuganzy ping

**Comment by blender** [comment]
@chuganzy another ping

**Comment by chuganzy** [comment]
Sorry I had no time to work on this for awhile.. I will continue working on this!

**Comment by ChristianSteffens** [comment]
pong

**Comment by ravitripathi** [comment]
Any updates on this? The build folder is a mess as of now.

**Comment by sidepelican** [comment]
What are the remain works?

**Comment by chuganzy** [comment]
Sorry I have been keeping this open for awhile.. Actually a lot has changed since I opened this PR, and now I have to also put static builds into consideration.. Probably redoing this from scratch..

**Comment by sidepelican** [comment]
I’m working for remaining tasks in this pr. 
fixing 
- bcsymbolmaps
- static framework 
- follow the master branch

**Pull request merged**
