### PR TITLE
Use NSRange initializer

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by Dschee** [comment]
Wow, looks like I'm gonna have to rebase many times, seeing you making the same changes I've already made in #2001 in smaller chunks ...

**Comment by ikesyo** [comment]
Because looks like you are not going to do that 🙂

**Comment by mdiep** [comment]
These will make the diff in #2001 much smaller, which is nice for reviewing!

**Comment by Dschee** [comment]
Well, thtat‘s true, go for it. No problem with this on my side, was just a little surprised at first sight. ^^

**Pull request merged**
