### PR TITLE
Add a first novice take on supporting -pre

### PR DESCRIPTION
**Pull request by pietbrauer**
This is related to https://github.com/Carthage/Carthage/issues/469 and
more than incomplete but I thought I might get some initial feedback to go along the correct path.

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Thanks for the pull request! :sparkles:

While it would be nice to support this, all that's necessary to fix https://github.com/Carthage/Carthage/issues/469 itself is just to make sure we ignore versions with trailing text (which is how the code is _supposed_ to behave right now, though it apparently broke).

If you do want to continue with the enhancement, we'll need to decide how prerelease software fits into semantic versioning constraints. My gut says that it kinda doesn't, because any prerelease version can have breaking changes, which defeats the purpose of Cartfile operators like `~>` and `>=`.

Is there a particular use case where you would _want_ to obtain a prerelease version, and yet don't want to refer to a tag by name?

**Comment by pietbrauer** [comment]
For me everything fits into Semantic Versioning:

>  Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format. - [semver.org](http://semver.org)

 A pre release version is a not yet fully released version with the new version number (so breaking changes are actually reflected).

The possible order would be `1.0.0 > 1.0.0-pre > 1.0.0-beta > 1.0.0-alpha`.

For me it is necessary for Carthage to support these else Semantic Versioning support is incompatible.

Does this make sense?

**Comment by jspahrsummers** [comment]
Sorry, yes, prerelease versions _are_ part of SemVer. What I meant is that it makes semantic version _constraints_ (`>=`, `~>`) confusing and potentially problematic (because many users will not want to receive prereleases).

Maybe we should only support `==` for version specifiers like this? But then what advantage would it have over specifying `"1.0.0-alpha"` as a tag name?

**Comment by pietbrauer** [comment]
Sounds legit. Thanks for clarifying.

**Comment by jspahrsummers** [comment]
No problem. Sorry it took so long to reply!

**Pull request closed without merging**
