### PR TITLE
Make Commandant and PrettyColors as the public dependencies of CarthageKit

### LINKED ISSUE #546: Code-signing Issue with Subcomponent
Hi,

I didn't previously have a Mac Developer certificate. I paid the $100 for the iOS one long ago but didn't see the need for the Mac one since I was just playing around with Mac Programming. Now that Apple is giving all paid members certificates for both platforms, I used Xcode 7 to grab the various developer certificates for the Mac. After grabbing them in Xcode 7, Xcode 6 can use the certificates and sign apps with them.

I'm currently building an app that builds on top of CarthageKit. Now that I'm telling Xcode to sign my app, I am getting an error that says a submodule is not signed at all inside CarthageKit. Its the argo submodule. The full error is pasted below:

```
CodeSign /Users/jeffberg/Library/Developer/Xcode/DerivedData/Cartwheel-ccadlvekthbkhmgrrvonizcoqfnp/Build/Products/Debug/Cartwheel.app/Contents/Frameworks/CarthageKit.framework/Versions/A
    cd /Users/jeffberg/Documents/SaturdayApps/Cartwheel/Cartwheel
    export CODESIGN_ALLOCATE=/Applications/Xcode-6.4-beta-3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    
Signing Identity:     "Mac Developer: Jeffrey Bergier (V78MM83472)"

    /usr/bin/codesign --force --sign EAE69B21A5DC4B4D165FE4A3B4DFE3E9910C95C9 --preserve-metadata=identifier,entitlements,resource-rules /Users/jeffberg/Library/Developer/Xcode/DerivedData/Cartwheel-ccadlvekthbkhmgrrvonizcoqfnp/Build/Products/Debug/Cartwheel.app/Contents/Frameworks/CarthageKit.framework/Versions/A

Warning: usage of --preserve-metadata with option "resource-rules" (deprecated in Mac OS X >= 10.10)!
/Users/jeffberg/Library/Developer/Xcode/DerivedData/Cartwheel-ccadlvekthbkhmgrrvonizcoqfnp/Build/Products/Debug/Cartwheel.app/Contents/Frameworks/CarthageKit.framework/Versions/A: code object is not signed at all
In subcomponent: /Users/jeffberg/Library/Developer/Xcode/DerivedData/Cartwheel-ccadlvekthbkhmgrrvonizcoqfnp/Build/Products/Debug/Cartwheel.app/Contents/Frameworks/CarthageKit.framework/Versions/A/Frameworks/Argo.framework
Command /usr/bin/codesign failed with exit code 1
```

I tried all of the suggestions in Issue #373 but nothing is working. I know you're busy and this is an open source project, so I really appreciate any help you can offer.

Thanks!
-Jeff

### PR DESCRIPTION
**Pull request by ikesyo**
~~Those should be in carthage app target directly, not in CarthageKit.~~

Hopefully fixes #546 and #673.

### CODE REVIEW

**Comment by mdiep** [comment]
How does this relate to #546?

I'm not sure that this is a good idea. Normally, separating these frameworks would be a good thing. But in this case, we copy 3 frameworks to `/Library/Frameworks` instead of just 1, which seems like it might lead to trouble. Maybe we should be copying these all into a single carthage-specific directory?

**Comment by ikesyo** [comment]
I'm sorry for the lack of the details. This is about

> However, the app was crashing until I added Commandant and PrettyColors (listed in your cartfile.private) to my Cartfile.

and might not be related to the code signing issue.

If the changes in this pull request isn't preferable, we sould make Commandant and PrettyColors as the public dependencies, not the private ones to address the issues.

**Comment by mdiep** [comment]
> If the changes in this pull request isn't preferable, we sould make Commandant and PrettyColors as the public dependencies, not the private ones instead to address the issues.

Ah, okay. That makes sense to me. What do you think?

**Comment by ikesyo** [comment]
That would be a simplest solution and looks OK to me, which can avoid complicating the `Makefile`.

**Comment by ikesyo** [comment]
I've modified the pull request. :zap:

**Comment by mdiep** [comment]
:metal:

**Pull request merged**
