### PR TITLE
Added support for tvOS

### PR DESCRIPTION
**Pull request by NachoSoto**
I've tested this with https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2333

screen shot 2015-09-09 at 22 43 33
screen shot 2015-09-09 at 22 44 02

### CODE REVIEW

**Comment by NachoSoto** [comment]
It looks like `TARGET_OS_IPHONE` is true when compiling with `SDKROOT` `appletvos` :hankey: 

screen shot 2015-09-09 at 22 26 09

**Comment by emaloney** [comment]
Yes, `TARGET_OS_IPHONE` includes _all of_ `TARGET_OS_IOS`, `TARGET_OS_TV`, and `TARGET_OS_WATCH`. (And `TARGET_OS_MAC` includes _all of those_, as well as `TARGET_OS_SIMULATOR` and `TARGET_OS_EMBEDDED`.) Not exactly intuitive.

(See lines 61-67 of `TargetConditionals.h` under the tvOS SDK.)

**Comment by NachoSoto** [comment]
Huh okay! Then I can workaround it, thanks @emaloney

**Comment by NachoSoto** [comment]
Okay this is ready now :)

**Comment by JaviSoto** [comment]
Perfect!

**Comment by mdiep** [comment]
This looks legit to me.

**Comment by mdiep** [comment]
Can anyone else verify that this works for them? I'm not set up to test against tvOS yet.

**Comment by mdiep** [comment]
Thanks for tackling this! :sparkling_heart:

**Pull request merged**
