### PR TITLE
Move dependencies for CLI tools into Cartfile.private

### PR DESCRIPTION
**Pull request by paulyoung**
As discussed with @jspahrsummers [on Twitter](https://twitter.com/py/status/566830853997613058).

### CODE REVIEW

**Comment by jspahrsummers** [comment]
Thanks @paulyoung! Were you still planning to remove the duplicate `xcconfigs` entry too?

**TLDR for others:** these dependencies are only used by `carthage`, not CarthageKit, so they shouldn't be exported to dependents of the latter.

**Comment by jspahrsummers** [comment]
Nevermind, just saw #332. This needs a merge now, though. :trollface:

**Comment by paulyoung** [comment]
:boom: :clap:

**Pull request merged**
