### PR TITLE
[WIP] Update LD_RUNPATH_SEARCH_PATHS and Makefile to setup separate rpaths for pkg installation and homebrew installation

### LINKED ISSUE #495: /Library/Frameworks takes priority over Homebrew installation
If you've installed Carthage from [the Homebrew formula](https://github.com/Homebrew/homebrew/blob/d1f70d44369de4d4998af351428f2b72e3dbf29d/Library/Formula/carthage.rb), you might expect that `carthage` would always use the version of CarthageKit installed from Homebrew.

Unfortunately, it seems like the executable always prioritizes loading frameworks from `/Library/Frameworks`, even though that's only populated from our package installer. This results in issues like #490.

We should update the formula and/or `Makefile` to prioritize custom framework locations over the “base” ones.

### PR DESCRIPTION
**Pull request by ikesyo**
I failed to reopen #935. :bow:

Fixes #495.

`"@executable_path/../Frameworks/$(OUTPUT_FRAMEWORK)/Versions/Current/Frameworks"` and `"/Library/Frameworks/$(OUTPUT_FRAMEWORK)/Versions/Current/Frameworks"` is before than `"@executable_path/../Frameworks"` and `"/Library/Frameworks"` to avoid conflicts between the nested dependencies and the same frameworks which are in `"@executable_path/../Frameworks"` and `"/Library/Frameworks"`.

### CODE REVIEW

**Comment by mdiep** [comment]
Is this still a work-in-progress?

**Comment by norio-nomura** [comment]
I think that `@loader_path/../Frameworks` should be removed that contained by Mac-Application.xcconfig, because that is harmful and useless.

### For package installed `carthage`
I think this PR does not fix that `carthage` installed by packaged loads `CarthageKit.framework` installed by Homebrew.
Because `carthage` installed by package still has `@loader_path/../Frameworks`.
that will be as following by this PR:
```sh
$ otool -l /usr/local/bin/carthage
…
Load command 31
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/../Frameworks (offset 12)
…
Load command 34
          cmd LC_RPATH
      cmdsize 88
         path /Library/Frameworks/CarthageKit.framework/Versions/Current/Frameworks (offset 12)
Load command 35
          cmd LC_RPATH
      cmdsize 32
         path /Library/Frameworks (offset 12)
```

`@loader_path/../Frameworks` points `/usr/local/Frameworks` on runtime, searched before `/Library/Frameworks`.
`brew install carthage` make a link `/usr/local/Frameworks/CarthageKit.framework/CarthageKit` pointing `/usr/local/Cellar/carthage/0.11/Frameworks/CarthageKit.framework/CarthageKit` and that will be loaded.

`@loader_path/../Frameworks` is harmful and should be removed.

### For Homebrew installed `carthage`
`LC_RPATH`s will be following on Homebrew installed `carthage` by this PR:
```sh
$ make prefix_install PREFIX=/usr/local/Cellar/carthage/0.11
…
$ otool -l /usr/local/Cellar/carthage/0.11/bin/carthage
…
Load command 31
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/../Frameworks (offset 12)
…
Load command 34
          cmd LC_RPATH
      cmdsize 96
         path @executable_path/../Frameworks/CarthageKit.framework/Versions/Current/Frameworks (offset 12)
Load command 35
          cmd LC_RPATH
      cmdsize 48
         path @executable_path/../Frameworks (offset 12)
```

#### On loading libraries that linked to `carthage`
`@loader_path/../Frameworks` points `/usr/local/Cellar/carthage/0.11/Frameworks` that is same to
`@executable_path/../Frameworks`.

#### On loading libraries that linked to `CarthageKit.framework` and not linked to `carthage`
Such as `Argo.framework`, the `@loader_path/../Frameworks` points `/usr/local/Cellar/carthage/0.11/Frameworks` and `Argo.framework` does not exist at there.

`@loader_path/../Frameworks` is not needed any library loading and may be removed.

### See also
I introduced fixes for similar situations on https://github.com/realm/SwiftLint/pull/244 and https://github.com/jpsim/SourceKitten/pull/110
This comment may be some explanation to https://github.com/jspahrsummers/xcconfigs/pull/52

**Comment by mdiep** [comment]
@ikesyo Are you still planning to work on this?

**Comment by ikesyo** [comment]
@mdiep I'm closing this for now. :bow:

**Pull request closed without merging**
