### PR TITLE
If a directory in repository caches is not a valid repository, remove that directory then clone the project

### LINKED ISSUE #694: A shell task failed with exit code 128 (Carthage 0.8)
I know this has cropped up in many other places but I'm seeing it now on some repos and not others.

```
$ carthage update --verbose
*** Fetching CocoaLumberjack
A shell task failed with exit code 128:
fatal: Not a git repository (or any of the parent directories): .git
```

This is with Cartfile declaration:
```
git "https://github.com/CocoaLumberjack/CocoaLumberjack.git" == 2.0.1
# Other variations tried that also fail
# github "CocoaLumberjack/CocoaLumberjack" == 2.0.1
# github "CocoaLumberjack/CocoaLumberjack" ~> 2.0
# github "CocoaLumberjack/CocoaLumberjack"
```

It does not appear that CocoaLumberjack has its own Cartfile therefore it is unlikely to be the transitive Cartfile with non-existent branch problem.

Most of my repos result in this git error. However the system is not totally broken, as I can successfully get Carthage to checkout and build a fork of ObjectiveSugar that I created (to add the project + scheme requirements for Carthage) - https://github.com/marcpalmer/ObjectiveSugar

Any ideas? Am I doing something wrong? Note that the error is "instantaneous" — it does not appear to go the network and there is nothing related to "CocoaLumberjack" under ./Carthage

Version proof:
```
$ carthage version
0.8.0
$ git version
git version 2.5.0
```

### PR DESCRIPTION
**Pull request by ikesyo**
Should fix #694, #642 and #407.

### CODE REVIEW

**Comment by mdiep** [comment]
Do you have any idea _why_ this happens?

**Comment by mdiep** [comment]
Never mind, I see that you answered that in a comment. :relaxed:

This looks good! :zap:

**Comment by ikesyo** [comment]
Thank you! ✨

**Comment by ikesyo** [comment]
We had a bug in this pull request :sob: :#752

**Pull request merged**
