### PR TITLE
Fix regression causing sorted build order to be lost

### PR DESCRIPTION
**Pull request by erichoracek**
This regressed in #1914

### CODE REVIEW

**Comment by mdiep** [comment]
Good catch! 😅

A test would definitely be great here if we can add one.

**Comment by erichoracek** [comment]
I've updated the `DependencyTest` frameworks to be dependent on one other, and updated the spec to verify their relative ordering—please take a look!

**Comment by BobElDevil** [comment]
Thanks for the test! looks good to me

**Comment by mdiep** [comment]
🤘

**Comment by ikesyo** [comment]
🙈 Thanks for the fix!

**Pull request merged**
