### PR TITLE
[SwiftLint] Remove `single_line_guard` custom rule

### PR DESCRIPTION
**Pull request by ikesyo**
It seems to me that the rule makes the readability worse.

### CODE REVIEW

**Comment by jdhealy** [comment]
The [regular expression as it stands](https://github.com/Carthage/Carthage/commit/7e625046b8a2fc2f5a6d1d81578072b41c0de9a8#diff-e9e9dfc22d31913c2e705d4d571d54c7R74) has, in practice, seemed bothersome to me, as well.

I do, however, see short single line guards as acceptable and very readable (at least, in my eyes) — <details><summary>examples from Swift Package Manager</summary>
```swift
git grep 'guard.*else.*\w' 'swift-package-manager/Sources/'
Basic/Lock.swift:        guard let fd = fd else { return }
Basic/PathShims.swift:    guard let resolvedPathStr = try? POSIX.realpath(pathStr) else { return path }
Basic/PathShims.swift:    guard rv == 0 else { throw SystemError.symlink(errno, path.asString, dest: destString) }
Basic/PathShims.swift:    guard rv == 0 else { throw SystemError.rename(errno, old: path.asString, new: dest.asString) }
Basic/PathShims.swift:    guard rv == 0 else { throw SystemError.unlink(errno, path.asString) }
Basic/PathShims.swift:                    guard shouldRecurse(path) else { continue }
Basic/PathShims.swift:                    guard let current = try? fileSystem.getDirectoryContents(path).makeIterator() else { continue }
Basic/Tuple.swift:    guard lhs.count == rhs.count else { return false }
Build/BuildPlan.swift:                guard case let .clang(target)? = targetMap[dependency] else { fatalError("unexpected clang module \(module)") }
Build/BuildPlan.swift:                guard let moduleMap = target.moduleMap else { break }
Commands/SwiftBuildTool.swift:            guard !graph.rootPackages[0].modules.isEmpty else { break }
Commands/SwiftPackageResolveTool.swift:            guard let deps = try? getDependencies(at: version) else { return nil }
Commands/SwiftPackageTool.swift:            guard !engine.hasErrors() else { return }
Commands/SwiftPackageTool.swift:            guard !engine.hasErrors() else { return }
Commands/SwiftPackageTool.swift:            guard !engine.hasErrors() else { return }
Commands/SwiftTool.swift:    guard POSIX.getenv("IS_SWIFTPM_TEST") == nil else { return nil }
Commands/SwiftTool.swift:    guard let env = POSIX.getenv("SWIFT_BUILD_PATH") else { return nil }
POSIX/getcwd.swift:    guard let path = String(validatingUTF8: cwd!) else { error() }
POSIX/realpath.swift:    guard rv != nil else { throw SystemError.realpath(errno, path) }
POSIX/realpath.swift:    guard let rvv = String(validatingUTF8: rv!) else { throw SystemError.realpath(-1, path) }
POSIX/rename.swift:    guard rv == 0 else { throw SystemError.rename(errno, old: old, new: new) }
POSIX/stat.swift:    guard rv == 0 else { throw SystemError.stat(errno, path) }
POSIX/stat.swift:    guard rv == 0 else { throw SystemError.stat(errno, path) }
POSIX/usleep.swift:    guard rv == 0 else { throw SystemError.usleep(errno) }
PackageDescription/Package.swift:        guard let dumpInfo = dumpInfo else { return }
PackageDescription/Package.swift:        guard fd != nil else { return }
PackageDescription4/Package.swift:        guard let dumpInfo = dumpInfo else { return }
PackageDescription4/Package.swift:        guard fd != nil else { return }
PackageDescription4/Version+StringLiteralConvertible.swift:        guard requiredComponents.count == 3 else { return nil }
PackageDescription4/Version+StringLiteralConvertible.swift:            guard let start = start else { return [] }
PackageGraph/DependencyResolver.swift:                guard self.error == nil else { return AnySequence([]) }
PackageGraph/DependencyResolver.swift:                    guard self.error == nil else { return AnySequence([]) }
PackageLoading/ManifestLoader.swift:        guard baseURL.chuzzle() != nil else { fatalError() }  //TODO
PackageLoading/ManifestLoader.swift:        guard isFile(path) else { throw PackageModel.Package.Error.noManifest(baseURL: baseURL, version: version?.description) }
PackageLoading/Module+PkgConfig.swift:    guard let pkgConfigName = module.pkgConfig else { return nil }
PackageLoading/Module+PkgConfig.swift:        guard let platform = Platform.currentPlatform else { return false }
PackageLoading/Module+PkgConfig.swift:            guard let brewPrefix = Static.value else { return [] }
PackageLoading/PackageBuilder.swift:            guard let target = targetMap[$0.name] else { return [] }
PackageLoading/PackageBuilder.swift:            guard !swiftSources.isEmpty else { return nil }
PackageLoading/PackageBuilder.swift:            guard swiftSources.isEmpty else { throw Module.Error.mixedSources(potentialModule.path.asString) }
PackageLoading/PackageBuilder.swift:            guard module.type == .test else { return false }
PackageLoading/PackageBuilder.swift:            guard !names.isEmpty else { throw Product.Error.noModules(product) }
PackageLoading/PackageDescription4Loader.swift:        guard case .dictionary(let topLevelDict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:        guard case .dictionary(let package)? = topLevelDict["package"] else { fatalError("missing package") }
PackageLoading/PackageDescription4Loader.swift:        guard case .string(let name)? = package["name"] else { fatalError("missing 'name'") }
PackageLoading/PackageDescription4Loader.swift:                guard case .int(let value) = $0 else { fatalError("swiftLanguageVersions contains non int element") }
PackageLoading/PackageDescription4Loader.swift:                guard case .string(let excludeString) = element else { fatalError("exclude contains non string element") }
PackageLoading/PackageDescription4Loader.swift:        guard case .dictionary(let dict) = json else { fatalError("Unexpected item") }
PackageLoading/PackageDescription4Loader.swift:            guard case .string(let identifier)? = requirementDict["identifier"] else { fatalError() }
PackageLoading/PackageDescription4Loader.swift:            guard case .string(let identifier)? = requirementDict["identifier"] else { fatalError() }
PackageLoading/PackageDescription4Loader.swift:            guard case .string(let identifier)? = requirementDict["identifier"] else { fatalError() }
PackageLoading/PackageDescription4Loader.swift:        guard case .dictionary(let dict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:        guard case .string(let name)? = dict["name"] else { fatalError("missing name") }
PackageLoading/PackageDescription4Loader.swift:        guard case .dictionary(let dict) = item else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:        guard case .string(let type)? = dict["type"] else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:            guard case .string(let name)? = dict["name"] else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:            guard case .string(let name)? = dict["name"] else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:            guard let package = dict["package"] else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:            guard case .string(let name)? = dict["name"] else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:    guard case .dictionary(let topLevelDict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescription4Loader.swift:    guard case .array(let errors)? = topLevelDict["errors"] else { fatalError("missing errors") }
PackageLoading/PackageDescription4Loader.swift:        guard case .string(let string) = error else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .dictionary(let topLevelDict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .dictionary(let package)? = topLevelDict["package"] else { fatalError("missing package") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .string(let name)? = package["name"] else { fatalError("missing 'name'") }
PackageLoading/PackageDescriptionLoader.swift:                guard case .int(let value) = $0 else { fatalError("swiftLanguageVersions contains non int element") }
PackageLoading/PackageDescriptionLoader.swift:                guard case .string(let excludeString) = element else { fatalError("exclude contains non string element") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .dictionary(let dict) = json else { fatalError("Unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .dictionary(let dict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .string(let name)? = dict["name"] else { fatalError("missing name") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .string(let value)? = dict["value"] else { fatalError("missing value") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .dictionary(let dict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .string(let name)? = dict["name"] else { fatalError("missing name") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .string(let name) = item else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .dictionary(let topLevelDict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .array(let array)? = topLevelDict["products"] else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .dictionary(let dict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .string(let name)? = dict["name"] else { fatalError("missing item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .string(let productType)? = dict["type"] else { fatalError("missing item") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .array(let targetsJSON)? = dict["modules"] else { fatalError("missing item") }
PackageLoading/PackageDescriptionLoader.swift:            guard case JSON.string(let string) = $0 else { fatalError("invalid item") }
PackageLoading/PackageDescriptionLoader.swift:    guard case .dictionary(let topLevelDict) = json else { fatalError("unexpected item") }
PackageLoading/PackageDescriptionLoader.swift:    guard case .array(let errors)? = topLevelDict["errors"] else { fatalError("missing errors") }
PackageLoading/PackageDescriptionLoader.swift:        guard case .string(let string) = error else { fatalError("unexpected item") }
PackageModel/ResolvedModels.swift:            guard case .target(let target) = $0 else { return nil }
SourceControl/GitRepository.swift:        guard isWorkingRepo else { return false }
TestSupport/MockDependencyResolver.swift:                guard case let .string(str) = arr[0] else { fatalError() }
TestSupport/MockDependencyResolver.swift:                    guard case let .string(str) = json else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .dictionary(dict) = json else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .string(identifier)? = dict["identifier"] else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard let requirement = dict["requirement"] else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .dictionary(dict) = json else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .string(identifier)? = dict["identifier"] else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .dictionary(versions)? = dict["versions"] else { fatalError() }
TestSupport/MockDependencyResolver.swift:            guard case let .array(depArray) = deps else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .dictionary(dict) = json else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .string(name)? = dict["name"] else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .array(constraints)? = dict["constraints"] else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .array(containers)? = dict["containers"] else { fatalError() }
TestSupport/MockDependencyResolver.swift:        guard case let .dictionary(result)? = dict["result"] else { fatalError() }
TestSupport/MockDependencyResolver.swift:            guard case let .string(str) = version else { fatalError() }
TestSupport/misc.swift:                guard isDirectory(srcDir) else { continue }
TestSupportExecutable/main.swift:        guard let fileLockOptions = options.fileLockOptions else { break }
Utility/ArgumentParser.swift:                guard let usage = argument.usage else { continue }
Utility/ArgumentParser.swift:                guard !parser.overview.isEmpty else { continue }
Utility/ArgumentParser.swift:                guard let usage = argument.usage else { continue }
Utility/ArgumentParser.swift:            guard let result = $1.get(option) else { return }
Utility/ArgumentParser.swift:            guard let result = $1.get(option) else { return }
Utility/ArgumentParser.swift:            guard let result = $1.get(positional) else { return }
Utility/ArgumentParser.swift:            guard let first = $1.get(first) else { return }
Utility/ArgumentParser.swift:            guard let second = $1.get(second) else { return }
Utility/ArgumentParser.swift:            guard let first = $1.get(first) else { return }
Utility/ArgumentParser.swift:            guard let second = $1.get(second) else { return }
Utility/ArgumentParser.swift:            guard let third = $1.get(third) else { return }
Utility/ArgumentParser.swift:            guard let result = $1.subparser(parser) else { return }
Utility/ArgumentParserShellCompletion.swift:        guard let commandName = commandName else { abort() }
Utility/PkgConfig.swift:            guard let line = uncommentedLine.chuzzle() else { continue }
Utility/PkgConfig.swift:            guard idx <= depString.characters.count - 1 else { return nil }
Utility/Platform.swift:        guard let uname = try? Process.checkNonZeroExit(args: "uname").chomp().lowercased() else { return nil }
Utility/Version.swift:        guard requiredComponents.count == 3 else { return nil }
Utility/Version.swift:            guard let start = start else { return [] }
Workspace/PinsStore.swift:        guard let pin = pinsMap[package] else { throw PinOperationError.notPinned }
Workspace/Workspace.swift:                guard let manifest = manifestsMap[url] else { return [] }
Workspace/Workspace.swift:            guard !protectedAssets.contains(name) else { continue }
Workspace/Workspace.swift:        guard case .checkout(let currentState) = dependency.state else { fatalError() }
Workspace/Workspace.swift:        guard !engine.hasErrors() else { return }
swiftpm-xctest-helper/main.swift:            guard case let testCaseSuite as XCTestSuite = $0 else { return nil }
swiftpm-xctest-helper/main.swift:                guard case let test as XCTestCase = test else { return nil }
```
</details>

I'm in favor of removing the regular expression rule and allowing us code reviews our own discretion in each case. But, not so much in favor of reverting every now-merged, single-line changes.

**Comment by ikesyo** [comment]
For example `guard let current = current else { return false }` wii be good but `guard FileManager.default.fileExists(atPath: frameworkFileURL.path) else { return SignalProducer(error: .readFailed(frameworkFileURL, nil)) }` is a bit difficult to read for me.

**Comment by ikesyo** [comment]
Reverted some changes since the original commit and replace some usages with explicit `if-let`.

**Comment by mdiep** [comment]
🤘

**Pull request merged**
