### PR TITLE
Copy frameworks to ${TARGET_BUILD_DIR}

### LINKED ISSUE #1203: Incorrect `copy-frameworks` target path for test targets in Xcode 7.3
It looks like Carthage currently copies frameworks to `${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}`. For _unit test targets_, these paths look something like this:

    /Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyAppTests.xctest/Frameworks/

However Xcode 7.3 installs the `.xctest` bundle in `${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}`. These paths look something like this:

    /Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/Frameworks/

So if you want to include Carthage framework dependencies in a unit test target, they will get installed into the wrong location, resulting in error messages like this when you try to run your tests:

    Failed to load test bundle from file:///Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/../MyAppTests.xctest/: Error Domain=NSCocoaErrorDomain Code=3587 "dlopen_preflight(/Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests): Library not loaded: @rpath/SomeThing.framework/SomeThing
      Referenced from: /Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests
      Reason: image not found" UserInfo={NSLocalizedFailureReason=The bundle is damaged or missing necessary resources., NSLocalizedRecoverySuggestion=Try reinstalling the bundle., NSFilePath=/Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests, NSDebugDescription=dlopen_preflight(/Users/you/Library/Developer/Xcode/DerivedData/MyApp-awbfmphajfrtkzejvntdixycauos/Build/Products/MyBuildConfig-iphonesimulator/MyApp.app/PlugIns/MyAppTests.xctest/MyAppTests): Library not loaded: @rpath/SomeThing.framework/SomeThing

Here’s what Apple’s [Xcode build settings documentation][buildsettingdocs] has to say about `TARGET_BUILD_DIR`:

[buildsettingdocs]: https://developer.apple.com/library/mac/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW88

> Run Script build phases that operate on product files of the target that defines them should use the value of this build setting. But Run Script build phases that operate on product files of other targets should use BUILT_PRODUCTS_DIR instead.

### PR DESCRIPTION
**Pull request by ali-rantakari**
Instead of copying frameworks to
${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}, copy them to
${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}.

This fixes `carthage copy-frameworks` for unit test targets in
Xcode 7.3, and should be fully backwards compatible as well (i.e., both
paths mentioned above should resolve to the same paths in older Xcode
versions.)

Fixes #1203.

### CODE REVIEW

**Comment by ikesyo** [comment]
#748 should be also addressed by this.

**Comment by mdiep** [comment]
Looks great! Thanks for the PR!

**Comment by brentleyjones** [comment]
Does this break extensions? https://github.com/Carthage/Carthage/issues/748#issuecomment-165159111

**Comment by mdiep** [comment]
I'm not sure. Would you be able to test that? I don't have a project with extensions handy.

**Pull request merged**
