### PR TITLE
Fix #452

### LINKED ISSUE #452: Document usage of local repository in Cartfile
During the development of a Carthage module, that would actually make sense to be able to reference a local repository. 
Instead of remotely checking a repo out, Carthage could simply copy the local repo in the Checkout folder or Symlink the repo in the checkouts folder

### PR DESCRIPTION
**Pull request by flovilmart**
Updates docs. with local repository example

### CODE REVIEW

**Comment by mdiep** [comment]
I doesn't seem right that this changed all the submodules.

**Comment by flovilmart** [comment]
That's better!

**Comment by robrix** [comment]
:+1:

**Comment by robrix** [comment]
Thanks very much @flovilmart!

**Pull request merged**
