### PR TITLE
Minor fixes - Address change request

### PR DESCRIPTION
**Pull request by blender**
Addressing change request form #2335 . 

Should it be italic (see: https://github.com/Carthage/Carthage/pull/2335#issuecomment-360536871) or is this enough?

### CODE REVIEW

**Comment by jdhealy** [comment]
I don’t have strong qualms against italics, but do prefer quotation marks, and definitely [am still against `<code>` tags](https://github.com/Carthage/Carthage/pull/2335#pullrequestreview-91601718).

**Comment by jdhealy** [comment]
Also, the [recently introduced GitHub coauthors feature](https://github.com/blog/2496-commit-together-with-co-authors) might fit well for this.

**Comment by blender** [comment]
@kant does appear as participant. I will try co-author in the next commit

**Comment by blender** [comment]
@jdhealy I'm not sure I follow on the <code> tags, I don't see any explicit <code> tags.  Do you mean backticks `` for non-code keywords?

**Comment by mdiep** [comment]
👍 to italics. I think that makes it stand out nicely.

**Comment by blender** [comment]
@mdiep should be ready. Please check the results here: https://github.com/Carthage/Carthage/tree/pull/2335

**Comment by mdiep** [comment]
Thanks @blender!

**Pull request merged**
