### PR TITLE
[Reference PR] Update spm support

### PR DESCRIPTION
**Pull request by yhkaplan**
This is a reference PR for #1945

### CODE REVIEW

**Comment by ikesyo** [comment]
As stated in https://github.com/Carthage/Carthage/pull/1945#issuecomment-429524493, this still seems WIP and there is another unaddressed feedback: https://github.com/Carthage/Carthage/pull/1945#issuecomment-309082053.

**Comment by yhkaplan** [comment]
@blender Sorry for the confusion! @ikesyo is correct. I'm hoping @devxoul will merge my PR into his existing one, then me or him can address any remaining feedback. 

(If he's too busy to respond, I suppose I'll go forward with this PR)

**Comment by blender** [comment]
I think we can merge to his PR from here. I actually don't know how to go about this.

The simplest way would be for @devxoul to accept the change on this branch.

**Comment by blender** [comment]
I mean the same way I checkout his pr from this remote I suppose I could also push to it.

**Comment by yhkaplan** [comment]
#1945 has been merged, so I'll go ahead and close this.

**Pull request closed without merging**
