### PR TITLE
Add bash/zsh completion scripts

### PR DESCRIPTION
**Pull request by yoichitgy**
I wrote bash/zsh completion scripts for Carthage as requested in Issue #500.

For now, I added the scripts and a draft version of README to `script/completion/` directory in the Carthage repository. I think still the following things are remained to do.

1. Decide where to store the scripts in the Carthage repository.
2. Modify installer settings (.pkg and brew) to include the scripts.
3. Update README to mention the bash/zsh completion.

### CODE REVIEW

**Comment by dcaunt** [comment]
FWIW I've been using the bash completion and it's great.

**Comment by mdiep** [comment]
> Decide where to store the scripts in the Carthage repository.

The `script/` directory is really meant for scripts related to bootstrapping and building the repository. It would probably be more appropriate to store them inside the `Source` directory inside a new subdirectory. Maybe `Source/Scripts/`?

**Comment by yoichitgy** [comment]
Thank you, @mdiep. I moved the completion scripts to Source/Scripts/ directory. If a more appropriate location is found, I'll change the location later. I'm going to update installer configurations of Carthage.

**Comment by yoichitgy** [comment]
I finished writing the auto completion scripts and updating the project to include them in .pkg installer.

## Auto completion scripts

The auto completion scripts are stored in `Source/Scripts/` directory as @mdiep mentioned.

## Project configuration

The scripts are installed to `/Library/Frameworks/CarthageKit.framework/Versions/A/Scripts/` directory. To setup the installation (or actually build of Carthage), I had two options to configure, and chose the first one.

A. Add `Source/Scripts/` directory and the scripts in it to the Xcode project of Carthage, and a `Copy Files Phase` to CarthageKit to copy the scripts into CarthageKit.framework.
B. Modify `Makefile` to copy the scripts into the temporary build directory.

I chose the former one because I think it is natural that the project file contains the scripts because they are stored in `**Source**/Scripts` directory. Also it looks easier to update when another person add new scripts in the future.

## Documentation

Documentation is added by Pull Request #855 to avoid displaying the document until a new version merging this PR is released.

**Comment by mdiep** [comment]
I'm not a shell expert, but this looks reasonable to me. :+1:

Thanks for doing this! :sparkles:

**Pull request merged**
