### PR TITLE
[WIP] Ability to build only one dependency

### PR DESCRIPTION
**Pull request by NachoSoto**
Solves #610

This is very much WIP.

## TODO:

- [ ] Figure out right API for this option.
- [ ] Figure out how this should interact with `skip-current`.
- [ ] Add unit tests.

### CODE REVIEW

**Comment by nickskull** [comment]
Are you still working on this? :)

**Comment by NachoSoto** [comment]
No, I have no time at the moment, so if anybody wants to take it from here feel free!

**Comment by pepibumur** [comment]
Hey @NachoSoto I'll keep with it :P

**Comment by NachoSoto** [comment]
Actually I wouldn't mind picking this up now that I can use Swift 2. It was a pain to do on Xcode 6 for various reasons.

**Pull request closed without merging**
