### PR TITLE
Include Swift compiler version in addition to swiftlang version and clang version

### PR DESCRIPTION
**Pull request by ikesyo**
That would be more comprehensible.

See also #1983 and #1984. ~~Originally I assumed this in [this comment](https://github.com/Carthage/Carthage/issues/1983#issuecomment-307257847).~~

### CODE REVIEW

**Comment by mdiep** [comment]
I'm not sure which is the best approach here. This is certainly more comprehensible. The current implementation is probably more correct, but perhaps not meaningfully so. Outside of some very small potential edge cases, I think these should behave the same.

What do you think @BobElDevil?

**Comment by ikesyo** [comment]
I'm concerned about Xcode patch version updates. For example (the below should not be actual values):

- Xcode 9.0
  - `4.0` and `swiftlang-900.0.43 clang-900.0.22.8`
- Xcode 9.0.1
  - `4.0` and `swiftlang-900.0.44 clang-900.0.22.9`

If we use the former a build cache will still be valid, but if we use the latter will not be valid anymore.

However, it may be safer to use the latter value if we take into account a situation that there is no binary compatibility between patch version updates.

**Comment by BobElDevil** [comment]
Yeah, incompatibility between patch versions is what I'm worried about too. So I think we should stick with the swiftlang/clang version. However I think for readability, we could take this opportunity to pull in both parts of the version string, so we can make more readable messaging. So while we still compare compiler versions, we still change it from:
`"Incompatible Swift version - framework was built with swiftlang-100.0.00 clang-100.0.00.1 and the local version is swiftlang-200.0.00 clang-200.0.00.2."`
to
`"Incompatible Swift version - framework was built with 3.0 (swiftlang-100.0.00 clang-100.0.00.1) and the local version is 3.1 (swiftlang-200.0.00 clang-200.0.00.2.")`

**Comment by mdiep** [comment]
> If we use the former a build cache will still be valid, but if we use the latter will not be valid anymore.

But _is_ the latter valid? I'm not sure that we can count on compatibility between patch versions.

**Comment by ikesyo** [comment]
> compatibility between patch versions

That will not be guaranteed. Also, I'm not sure if swiftlang/clang versions are bumped between patch versions.

**Comment by mdiep** [comment]
I think we should stick with the current implementation because it's safer. But I think it'd be fine to pull in the Swift version like @BobElDevil suggested.

**Pull request merged**
