### PR TITLE
Add Allow HTTP Flag

### PR DESCRIPTION
**Pull request by hlineholm**
This is a proposal for a solution to the problem described in #1885. I have the exact same problem and as I think Carthage should safeguard its users, there should be an option available to use HTTP at your own risk. (As I worked with the changes in this PR, I discovered that http is allowed for enterprise GitHub URLs but the validation for this seems to be pretty fragile as it only relies on a certain combination of path components in the url.) 

This issue is so big for us that we cannot use Carthage unless this is implemented.

### CODE REVIEW

**Comment by blender** [comment]
The code looks good to me. This however doesn't mean I agree with the change since it's promoting a bad practice that can quickly spread.

You can issue your own TLS certificates and even create your own CA an trust it. So adding encryption to your internal hosts seems doable to me.

**Comment by hlineholm-flir** [comment]
@blender yes it is easy to do if you own your host but I don't. It could take months (or worse before) they who own it decides to or has the time to fix it.

Not sure why [#3244.1](https://travis-ci.org/Carthage/Carthage/jobs/494357636) fails. It didn't fail when I ran `make tests`.

**Comment by mdiep** [comment]
> there should be an option available to use HTTP at your own risk.

The issue is that you're not just putting yourself at risk: the users of your app are also at risk.

> http is allowed for enterprise GitHub URLs

We should address this as well.

---

There's no reason to use HTTP. It's dangerous. I don't think we should support it because teams don't want to generate a free SSL certificate and deploy it to their backends.

**Comment by hlineholm** [comment]
The risks are well known and the use of *http* should be limited. But I think to totally forbid it is outside the scope of Carthage. By making it default to not allow *http* (similar to *curl*), Carthage does what it can to make the world safer. 

Does [CocoaPods](http://cocoapods.org) enforce *https*? [Gradle](https://gradle.org) has a [plugin](https://http-builder-ng.github.io/gradle-http-plugin/) which makes it possible to run *http* requests. [ATS](https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33) by default doesn't allow *http* but have a *NSExceptionAllowsInsecureHTTPLoads* option for specified domains.

**Comment by blender** [comment]
@hlineholm I understand that you need this patch.

Why not just keep your fork up to date and distribute a .pkg from there?

**Comment by hlineholm** [comment]
Yes @blender that is what I'm going to do. So I'll manage and it should be possible for others who needs to do the same thing to use [hlineholm/allow-http](
https://github.com/hlineholm/Carthage/tree/hlineholm/allow-http). 

But I wanted to evaluate this with you guys first, I mean for not having to keep this fork up to date 🙂

**Comment by hlineholm** [comment]
So I discovered that when parsing a *framework.json* containing *http* schemes, the BuildCommand needs to know if *http* should be allowed. This gave me a build error from Argo:

> "Build.swift:65:5: The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions"

**Comment by hlineholm** [comment]
@ikesyo seems to be VSCode that messes it up by using spaces instead of tabs. I'll fix it...

**Pull request closed without merging**
