### PR TITLE
Update to RAC 4.2.1

### LINKED ISSUE #1370: Carthage Update Freezes, Sometimes
Whenever I run `carthage update`, it freezes after logging "*** Fetching izevent". But it worked one time. Commenting out lines from the Cartfile one by one increases the chances of a successful build. Running on a 2012 Mac mini quad core i7 with OS X 10.11.5.

To be clear, there's an element of chance here. Sometimes it locks up, sometimes it doesn't. The more libraries I add to my Cartfile, the higher the chance it'll freeze up.

* `carthage version`: 0.17.1
* `xcodebuild -version`: 7.3.0 (and 7.3.1)
* Are you using `--no-build`? no
* Are you using `--no-use-binaries`? no
* Are you using `--use-submodules`? no

**Cartfile**
```
github "izeni-team/izevent" ~> 0.3.0
github "xmartlabs/Eureka" ~> 1.6
github "adamwaite/Validator"
github "intuit/LocationManager"
github "jdg/MBProgressHUD" ~> 0.9.2
github "realm/realm-cocoa" ~> 1.0
github "iziz/libPhoneNumber-iOS"
github "mamaral/Neon"
github "izeni-team/izeni-ios" ~> 0.9
```

**Carthage Output**
```
*** Fetching izeni-ios
*** Fetching Neon
*** Fetching libPhoneNumber-iOS
*** Fetching realm-cocoa
*** Fetching MBProgressHUD
*** Fetching LocationManager
*** Fetching Validator
*** Fetching Eureka
*** Fetching izevent
```

Carthage 0.16.2 and 0.16.1 and 0.13.0 don't have this problem, as far as I can tell. I'm using 0.16.2 as a temporary workaround.

### PR DESCRIPTION
**Pull request by mdiep**
Fixes #1370

### CODE REVIEW

**Comment by NachoSoto** [comment]
🎉 

Man, Travis is slow...

**Comment by ikesyo** [comment]
Finally Travis passed! 😂

**Comment by mdiep** [comment]
😂

**Comment by sam-w** [comment]
<3 thanks for the fix on this. I was tearing my hair out.

**Pull request merged**
