### PR TITLE
[xcodebuild] Disable Code Coverage explicitly

### LINKED ISSUE #2056: Targets built with coverage data in Xcode 9
One of my test builds I just submitted to iTunes Connect (built with Xcode 9) failed processing with the following message:

> **Invalid Bundle** - Disallowed LLVM instrumentation. Do not submit apps with LLVM profiling instrumentation or coverage collection enabled. Turn off LLVM profiling or code coverage, rebuild your app and resubmit the app.

This is caused by [this issue](https://forums.developer.apple.com/thread/81893). The new Xcode seems to build coverage data into all builds, not only for testing. From the changelog:

> Schemes with Code Coverage enabled (in the Test action) will now always build with Code Coverage, including for the Run and Launch actions. This reduces the need to build multiple versions of the application. Users who require code coverage to be off for their non-test actions can explicitly use a separate scheme with coverage disabled. (31848014)

When building frameworks during the "Archive" action Xcode seems to handle that. But since Carthage dependencies are built externally and copied into the bundle later, they still contain coverage data.

Somehow the Carthage build process needs to make sure that gathering coverage data is disabled during build, even though it's enabled in the project.

### PR DESCRIPTION
**Pull request by ikesyo**
Should fix #2056.

### CODE REVIEW

**Comment by ikesyo** [comment]
Hmm `-enableCodeCoverage` option is only permitted on test action (at least with Xcode 8). :disappointed:

**Comment by ikesyo** [comment]
So this may be impossible without modifying schemes but that should not be an option.

**Comment by mdiep** [comment]
It's not clear to me that this is something that we should fix. (It should maybe be on the framework authors to fix their schemes.) I think that's probably the best solution.

But if we wanted to, we could probably check the Xcode version to conditionally pass `-enableCodeCoverage`?

**Comment by ikesyo** [comment]
> But if we wanted to, we could probably check the Xcode version to conditionally pass `-enableCodeCoverage`?

This didn't work for Xcode 9 either.

**Comment by frankschlegel** [comment]
Wow, that was dismissed a bit too fast, I think.
@mdiep You say _every_ framework author should disable code coverage generation in their project to be compatible with Carthage? Not sure if this is going to happen anytime soon…

It seems Xcode does not generate coverage data when using the "Archive" action. Can Carthage maybe somehow leverage that?

**Comment by mdiep** [comment]
> You say every framework author should disable code coverage generation in their project to be compatible with Carthage?

That seems like it's more-or-less the intent of the Xcode team.

> Users who require code coverage to be off for their non-test actions can explicitly use a separate scheme with coverage disabled

**Comment by frankschlegel** [comment]
I don't think so. They explicitly enabled it everywhere now because they think the users might want to get coverage data outside of the test target. But they didn't consider external build systems.

**Comment by frankschlegel** [comment]
I think a good fix for Carthage to work around this is to actually disable that option in the scheme. Normally you're not supposed to use Carthage's checkouts aside from building your dependencies anyways, right?

**Comment by ikesyo** [comment]
Using `archive` action is not an option, unfortunately: https://github.com/Carthage/Carthage/issues/169#issuecomment-68624884

**Comment by ikesyo** [comment]
> I think a good fix for Carthage to work around this is to actually disable that option in the scheme. 

I believe modifying checkouts (making checkouts dirty) should be strongly avoided.

**Comment by frankschlegel** [comment]
I see. Can you somehow "remove" the `-fprofile-instr-generate -fcoverage-mapping` parameters from the build?

**Comment by ikesyo** [comment]
We are not sure. It would be great if you could detect the way to do that.

**Comment by TofPlay** [comment]
Did you see this [Technical Q&A QA1964 - LLVM Instrumentation](https://developer.apple.com/library/content/qa/qa1964/_index.html)?

**Pull request closed without merging**
