### PR TITLE
Static frameworks support information in README.

### LINKED ISSUE #2497: README is missing info about building Swift static libraries
There are obvious traces of work happening in this direction ( #1935 , #2285 ), but I personally struggle with accumulating any particular results of it.

### PR DESCRIPTION
**Pull request by isaac-weisberg**
Add a notice and the description of static framework support being introduced into the project's features.
Resolves #2497 .

### CODE REVIEW

**Comment by blender** [comment]
One question on the process, copy-frameworks strips debug symbols. 

Does everything get stripped properly in the strip phase of the app instead?

**Comment by isaac-weisberg** [comment]
@blender indeed, it's a great question and it's my responsibility to look into it.

**Comment by isaac-weisberg** [comment]
@blender we have experimented with the workflow process at work and we can confirm that we have successfully been able to include a statically linked framework into an iOS application, archive it with the release configuration and successfully upload it as an application version. We have not seen any deviation or increase in AppStore downloadable/unpacked size, however we have not been able to observe the behavior of the code stripping mechanism as well as confirm absence of presence of debugging symbols in the exported archive. Funny enough, we have not been able to confirm presence or absence of debugging symbols... like... at all! But we have accumulated our observations.

- Carthage launches `xcodebuild` with `-C Release` (which is not news, I am just mentioning this here)
- Attempting to navigate to declared-in-framework-class' declaration causes the editor to navigate to swift module's declaration summary instead of the source code. Not really sure whether if it is supposed to navigate to source code if the binary was compiled with debugging symbols, but just for the case if it is, it doesn't do that.

Dependencies' project's target `Build Settings` feature some shady stuff.
- COPY_PHASE_STRIP=NO
- STRIP_INSTALLED_PRODUCT=YES
- STRIP_STYLE=debugging
- STRIP_SWIFT_SYMBOLS=YES

My only thought right now is to set "Strip debug symbols during copy (COPY_PHASE_STRIP)" for release configuration and try to `carthage build --no-skip-current` and try to inspect any difference it makes. Which I am about to be starting to do riiiiight now :)

**Comment by isaac-weisberg** [comment]
```
Isaacs-Mac-mini:ResourceQueue.framework isaac_weisberg$ pwd
/Users/isaac_weisberg/Projects/ResourceQueue/Carthage/Build/iOS/Static/ResourceQueue.framework
Isaacs-Mac-mini:ResourceQueue.framework isaac_weisberg$ dsymutil -s ResourceQueue
Cannot get 'ResourceQueue' as MachO file: The file was not recognized as a valid object file
Isaacs-Mac-mini:ResourceQueue.framework isaac_weisberg$ dsymutil -s Modules/ResourceQueue.swiftmod
ule/arm64.swiftmodule
Cannot get 'Modules/ResourceQueue.swiftmodule/arm64.swiftmodule' as MachO file: The file was not r
ecognized as a valid object file
```
Am I doing it wrong?

**Comment by isaac-weisberg** [comment]
There is no `.framework` size difference from COPY_PHASE_STRIP=NO switched to YES.

**Comment by blender** [comment]
try 
- `nm  -arch armv7 -a ResourceQueue | grep -w "SO"`
- `nm -arch armv7 -a ResourceQueue | grep -w "OSO"`

- `ar -x ResourceQueue` and then dsymutil -s on one of the unpacked files

**Comment by isaac-weisberg** [comment]
It becomes dangerous to just copy-and-paste, will indefinitely have to learn all of this stuff.

**Comment by blender** [comment]
> There is no .framework size difference from COPY_PHASE_STRIP=NO switched to YES.

COPY_PHASE_STRIP=YES/NO does not influence anything on the dependency. 

it does make a difference in your app in combination with `carthage copy-frameworks`.

Is `STRIP_INSTALLED_PRODUCT=YES`  set in your App ?

**Comment by isaac-weisberg** [comment]
```
Isaacs-Mac-mini:ResourceQueue.framework isaac_weisberg$ pwd
/Users/isaac_weisberg/Projects/ResourceQueue/Carthage/Build/iOS/Static/ResourceQueue.framework

Isaacs-Mac-mini:ResourceQueue.framework isaac_weisberg$ nm -arch armv7 -a ResourceQueue | grep -w "SO"

Isaacs-Mac-mini:ResourceQueue.framework isaac_weisberg$ nm -arch armv7 -a ResourceQueue | grep -w "OSO"

Isaacs-Mac-mini:ResourceQueue.framework isaac_weisberg$ ar -x ResourceQueue
ar: ResourceQueue is a fat file (use libtool(1) or lipo(1) and ar(1) on it)
ar: ResourceQueue: Inappropriate file type or format
```
First two `nm`'s did not print anything.
`STRIP_INSTALLED_PRODUCT` is set to `YES` in the application target's build settings.

**Comment by blender** [comment]
I believe debug symbols are stripped. You can check in your app's .DSYM is there is any trace of `ResourceQueue` using `dsymutil`

> ar: ResourceQueue is a fat file (use libtool(1) or lipo(1) and ar(1) on it)
ar: ResourceQueue: Inappropriate file type or format

- `lipo -thin armv7  ResourceQueue -output armv7ResourceQueue`
- `ar -x  armv7ResourceQueue`
- `dsymutil -s <some extracted file>`

**Comment by isaac-weisberg** [comment]
```
Isaacs-Mac-mini:ResourceQueue.framework isaac_weisberg$ dsymutil -s ResourceQueue.o
----------------------------------------------------------------------
Symbol table for: 'ResourceQueue.o' (armv7)
----------------------------------------------------------------------
Index    n_strx   n_type             n_sect n_desc n_value
======== -------- ------------------ ------ ------ ----------------
[     0] 00000414 0e (     SECT    ) 04     0000   0000000000000ef0 'l_metadata'
[     1] 00000ad0 0e (     SECT    ) 04     0000   0000000000000f04 'l_metadata.7'
[     2] 00000a13 0e (     SECT    ) 01     0000   0000000000000e10 '__T013ResourceQueueAAC7dequeueq_Sgx2at_tFSbx_q_t_tcfU_TA'
[     3] 00000a4c 0e (     SECT    ) 01     0000   00000000000009c0 '__T0xq_Sbs5Error_pIgiidzo_x_q_tSbsAA_pIgidzo_s8HashableRzr0_lTRTA'
[     4] 000006a6 0e (     SECT    ) 01     0000   0000000000000a0c '__T013ResourceQueueytWh2_'
[     5] 00000bc5 0e (     SECT    ) 04     0000   0000000000000f18 'l_metadata.10'
[     6] 00000b64 0e (     SECT    ) 04     0000   0000000000000f2c 'l_metadata.13'
[     7] 000009de 0e (     SECT    ) 01     0000   0000000000000a80 '__T013ResourceQueueAAC6removeyx2at_tFSbx_q_t_tcfU_TA'
[     8] 00000b1f 0e (     SECT    ) 01     0000   0000000000000dfc '__T0xq_Sbs5Error_pIgiidzo_x_q_tSbsAA_pIgidzo_s8HashableRzr0_lTRTA.14'
[     9] 0000068c 0e (     SECT    ) 01     0000   0000000000000ca8 '__T013ResourceQueueytWh6_'
[    10] 00000001 0e (     SECT    ) 01     0000   000000000000099c 'l_objectdestroy'
[    11] 00000a8e 0e (     SECT    ) 01     0000   0000000000000a70 'l_objectdestroy.9'
[    12] 00000b8f 0e (     SECT    ) 01     0000   0000000000000aac 'l_objectdestroy.12'
[    13] 0000020a 0e (     SECT    ) 01     0000   0000000000000ad0 'l_get_field_types_ResourceQueue'
[    14] 0000022a 0e (     SECT    ) 01     0000   0000000000000b9c 'l_create_generic_metadata_ResourceQueue'
[    15] 00000aeb 0e (     SECT    ) 01     0000   0000000000000e0c 'l_objectdestroy.6'
[    16] 00000120 0e (     SECT    ) 03     0020   0000000000000e70 'l__swift3_reflection_descriptor'
[    17] 00000afd 0e (     SECT    ) 03     0020   0000000000000e90 'l__swift3_reflection_descriptor.5'
[    18] 00000aa0 0e (     SECT    ) 03     0020   0000000000000eb0 'l__swift3_reflection_descriptor.8'
[    19] 00000ba2 0e (     SECT    ) 03     0020   0000000000000ed0 'l__swift3_reflection_descriptor.11'
[    20] 00000add 0e (     SECT    ) 05     0000   0000000000000f40 'l___unnamed_6'
[    21] 00000ac2 0e (     SECT    ) 05     0000   0000000000000f60 'l___unnamed_7'
[    22] 00000252 0e (     SECT    ) 07     0000   0000000000001034 'l__IVARS__TtC13ResourceQueue13ResourceQueue'
[    23] 000002d0 0e (     SECT    ) 0c     0000   00000000000011f0 'l_llvm.embedded.module'
[    24] 000002c1 0e (     SECT    ) 0d     0000   000000000000a630 'l_llvm.cmdline'
[    25] 000005c5 0f (     SECT EXT) 01     0020   0000000000000994 '__T013ResourceQueue07GenericA9CollectorCACyxq_q0_GSi6length_q_xcq0_xctcfcfA_'
[    26] 00000612 0f (     SECT EXT) 01     0020   000000000000098c '__T013ResourceQueue0A17CollectorStringedCACyxGSi6length_xSSctcfcfA_'
[    27] 00000316 1f (PEXT SECT EXT) 05     0000   0000000000001018 '__T013ResourceQueueAAC11queueLengthSivpWvd'
[    28] 000007d0 0f (     SECT EXT) 01     0020   00000000000005c8 '__T013ResourceQueueAAC5cleanyyF'
[    29] 00000341 1f (PEXT SECT EXT) 05     0000   0000000000001014 '__T013ResourceQueueAAC5queueSayx_q_tGvpWvd'
[    30] 0000085c 0f (     SECT EXT) 01     0020   0000000000000604 '__T013ResourceQueueAAC6removeyx2at_tF'
[    31] 0000055b 1f (PEXT SECT EXT) 01     00c0   00000000000007d4 '__T013ResourceQueueAAC6removeyx2at_tFSbx_q_t_tcfU_'
[    32] 00000882 0f (     SECT EXT) 01     0020   000000000000039c '__T013ResourceQueueAAC7dequeueq_Sgx2at_tF'
[    33] 0000058e 1f (PEXT SECT EXT) 01     00c0   0000000000000df8 '__T013ResourceQueueAAC7dequeueq_Sgx2at_tFSbx_q_t_tcfU_'
[    34] 00000801 0f (     SECT EXT) 01     0020   00000000000002dc '__T013ResourceQueueAAC7enqueueyq_8resource_x3fortF'
[    35] 000007ae 1f (PEXT SECT EXT) 01     0000   0000000000000134 '__T013ResourceQueueAAC7recoveryyF'
[    36] 000008c3 0f (     SECT EXT) 01     0020   00000000000002d4 '__T013ResourceQueueAAC9setLengthySiF'
[    37] 0000098b 0f (     SECT EXT) 01     0020   000000000000001c '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfC'
[    38] 000003e1 0f (     SECT EXT) 01     0020   00000000000000e8 '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfc'
[    39] 00000656 0f (     SECT EXT) 01     0020   0000000000000014 '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfcfA_'
[    40] 000008e8 1f (PEXT SECT EXT) 0b     00a0   00000000000011bc '__T013ResourceQueueAACMF'
[    41] 0000073e 1f (PEXT SECT EXT) 09     0080   0000000000001068 '__T013ResourceQueueAACMP'
[    42] 00000542 0f (     SECT EXT) 01     0020   00000000000000a4 '__T013ResourceQueueAACMa'
[    43] 000001e0 0f (     SECT EXT) 05     0020   0000000000000f74 '__T013ResourceQueueAACMn'
[    44] 00000972 0f (     SECT EXT) 01     0020   0000000000000968 '__T013ResourceQueueAACfD'
[    45] 0000036c 0f (     SECT EXT) 01     0020   0000000000000950 '__T013ResourceQueueAACfd'
[    46] 0000075f 1f (PEXT SECT EXT) 09     0080   00000000000011a4 '__T0s14CountableRangeVySiGAByxGs0B10ExpressionsWL'
[    47] 00000791 1f (PEXT SECT EXT) 09     0080   00000000000011a0 '__T0s14CountableRangeVySiGML'
[    48] 00000176 1f (PEXT SECT EXT) 01     00c0   0000000000000ce4 '__T0s26RangeReplaceableCollectionPsE14removeSubrangeyqd__s0A10ExpressionRd__5BoundQyd__5IndexRtzlFTf4gn_n'
[    49] 00000140 1f (PEXT SECT EXT) 05     00a0   000000000000101c '___swift_reflection_version'
[    50] 000000a8 1f (PEXT SECT EXT) 01     00c0   00000000000000d4 '_swift_rt_swift_allocObject'
[    51] 00000074 1f (PEXT SECT EXT) 01     00c0   00000000000009ac '_swift_rt_swift_deallocObject'
[    52] 00000443 1f (PEXT SECT EXT) 01     00c0   0000000000000c6c '_swift_rt_swift_getGenericMetadata'
[    53] 000000d8 1f (PEXT SECT EXT) 01     00c0   0000000000000c58 '_swift_rt_swift_getInitializedObjCClass'
[    54] 0000027e 1f (PEXT SECT EXT) 01     00c0   0000000000000000 '_swift_rt_swift_release'
[    55] 000003b5 1f (PEXT SECT EXT) 01     00c0   0000000000000c80 '_swift_rt_swift_slowAlloc'
[    56] 00000385 1f (PEXT SECT EXT) 01     00c0   0000000000000c94 '_swift_rt_swift_slowDealloc'
[    57] 0000003c 01 (     UNDF EXT) 00     0000   0000000000000000 '_OBJC_CLASS_$_SwiftObject'
[    58] 00000056 01 (     UNDF EXT) 00     0000   0000000000000000 '_OBJC_METACLASS_$_SwiftObject'
[    59] 000006f8 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0BbWV'
[    60] 00000701 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0Bi32_WV'
[    61] 000006ef 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0BoWV'
[    62] 000009be 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0S2ayxGx12arrayLiterald_tcfC'
[    63] 000006c0 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0Sa22_allocateUninitializedSayxG_SpyxGtSiFZ'
[    64] 000001f9 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0Sa5countSivg'
[    65] 000007f0 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0Sa6appendyxF'
[    66] 000008ac 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0Sa6removexSi2at_tF'
[    67] 00000834 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0Sa9removeAllySb15keepingCapacity_tF'
[    68] 00000511 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0SaMa'
[    69] 000004ab 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0SayxGs10CollectionsWa'
[    70] 00000481 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0SayxGs26RangeReplaceableCollectionsWa'
[    71] 000004f1 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0SayxGs8SequencesWa'
[    72] 00000757 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0SiN'
[    73] 00000727 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0Sis10StrideablesWP'
[    74] 0000070d 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0Sis13SignedIntegersWP'
[    75] 00000508 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0SqMa'
[    76] 00000901 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0s10CollectionPsE5index5IndexQzSgSb7ElementQzKc5where_tKF'
[    77] 0000051a 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0s14CountableRangeVMa'
[    78] 000004c5 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0s14CountableRangeVyxGs0B10ExpressionsWa'
[    79] 00000533 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0s5RangeVMa'
[    80] 0000093e 01 (     UNDF EXT) 00     0000   0000000000000000 '__T0s8SequencePsE5first7ElementQzSgSbAEKc5where_tKF'
[    81] 000002e7 01 (     UNDF EXT) 00     0000   0000000000000000 '__objc_empty_cache'
[    82] 000000c4 01 (     UNDF EXT) 00     0000   0000000000000000 '__swift_allocObject'
[    83] 00000092 01 (     UNDF EXT) 00     0000   0000000000000000 '__swift_deallocObject'
[    84] 00000466 01 (     UNDF EXT) 00     0000   0000000000000000 '__swift_getGenericMetadata'
[    85] 00000100 01 (     UNDF EXT) 00     0000   0000000000000000 '__swift_getInitializedObjCClass'
[    86] 00000296 01 (     UNDF EXT) 00     0000   0000000000000000 '__swift_release'
[    87] 000003cf 01 (     UNDF EXT) 00     0000   0000000000000000 '__swift_slowAlloc'
[    88] 000003a1 01 (     UNDF EXT) 00     0000   0000000000000000 '__swift_slowDealloc'
[    89] 0000041f 01 (     UNDF EXT) 00     0000   0000000000000000 '_swift_allocateGenericClassMetadata'
[    90] 000002a6 01 (     UNDF EXT) 00     0000   0000000000000000 '_swift_bridgeObjectRelease'
[    91] 0000015c 01 (     UNDF EXT) 00     0000   0000000000000000 '_swift_bridgeObjectRetain'
[    92] 000002fa 01 (     UNDF EXT) 00     0000   0000000000000000 '_swift_deallocClassInstance'
[    93] 00000b72 01 (     UNDF EXT) 00     0000   0000000000000000 '_swift_getTupleTypeMetadata2'
[    94] 00000011 01 (     UNDF EXT) 00     0000   0000000000000000 '_swift_initClassMetadata_UniversalStrategy'
```
How's it looking? God, I wish one day I will know and understand all of it!..

**Comment by blender** [comment]
if you see `N_` that's a debug symbol which makes sense __if you're checking the built library not yet statically linked into the app__. 

Once linked, since you have "STRIP_INSTALLED_PRODUCTS=YES"  (and hopefully [it's friends too]( https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW4)) debug symbols should be gone from your library and packed into the dSYM

**Comment by blender** [comment]
So, long story short, everything seems cool to me. Debug symbols are not there.

**Comment by isaac-weisberg** [comment]
```
Mac-mini-Endoral:DWARF endoral$ pwd
/Users/endoral/Library/Developer/Xcode/Archives/2018-06-26/Cutie 26.06.2018, 17.08.xcarchive/dSYMs/Cutie.app.dSYM/Contents/Resources/DWARF

Mac-mini-Endoral:DWARF endoral$ dsymutil -s Cutie | grep "ResourceQueue"
[  2764] 0002df67 1e (PEXT SECT    ) 01     0000   00000000000ae3a0 '__T013ResourceQueueAAC7recoveryyF'
[  2765] 0002df89 1e (PEXT SECT    ) 01     0080   00000000000aea40 '__T013ResourceQueueAAC6removeyx2at_tFSbx_q_t_tcfU_'
[  2767] 0002dffe 0e (     SECT    ) 01     0000   00000000000aec64 '__T013ResourceQueueytWh2_'
[  2768] 0002e018 0e (     SECT    ) 01     0000   00000000000aecd8 '__T013ResourceQueueAAC6removeyx2at_tFSbx_q_t_tcfU_TA'
[  2770] 0002e070 0e (     SECT    ) 01     0000   00000000000aeec4 '__T013ResourceQueueytWh6_'
[  2773] 0002e139 0e (     SECT    ) 01     0000   00000000000af028 '__T013ResourceQueueAAC7dequeueq_Sgx2at_tFSbx_q_t_tcfU_TA'
[  3920] 0003a9f5 1e (PEXT SECT    ) 08     0000   0000000000104b24 '__T013ResourceQueueAAC5queueSayx_q_tGvpWvd'
[  3921] 0003aa20 1e (PEXT SECT    ) 08     0000   0000000000104b28 '__T013ResourceQueueAAC11queueLengthSivpWvd'
[  4031] 0003b91f 1e (PEXT SECT    ) 0b     0080   000000000010a9c0 '__T013ResourceQueueAACMF'
[  5158] 00046c92 1e (PEXT SECT    ) 22     0080   000000000012a33c '__T013ResourceQueueAACySS7PromiseACCySo7UIImageCGGML'
[  5582] 0004d729 1e (PEXT SECT    ) 22     0080   000000000012b290 '__T013ResourceQueueAACMP'
[  6073] 000526fa 0f (     SECT EXT) 01     0000   00000000000aec00 '__T013ResourceQueue07GenericA9CollectorCACyxq_q0_GSi6length_q_xcq0_xctcfcfA_'
[  6074] 00052747 0f (     SECT EXT) 01     0000   00000000000aebf8 '__T013ResourceQueue0A17CollectorStringedCACyxGSi6length_xSSctcfcfA_'
[  6075] 0005278b 0f (     SECT EXT) 01     0000   00000000000ae834 '__T013ResourceQueueAAC5cleanyyF'
[  6076] 000527ab 0f (     SECT EXT) 01     0000   00000000000ae870 '__T013ResourceQueueAAC6removeyx2at_tF'
[  6077] 000527d1 0f (     SECT EXT) 01     0000   00000000000ae608 '__T013ResourceQueueAAC7dequeueq_Sgx2at_tF'
[  6078] 000527fb 0f (     SECT EXT) 01     0000   00000000000ae548 '__T013ResourceQueueAAC7enqueueyq_8resource_x3fortF'
[  6079] 0005282e 0f (     SECT EXT) 01     0000   00000000000ae540 '__T013ResourceQueueAAC9setLengthySiF'
[  6080] 00052853 0f (     SECT EXT) 01     0000   00000000000ae29c '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfC'
[  6081] 00052886 0f (     SECT EXT) 01     0000   00000000000ae354 '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfc'
[  6082] 000528b9 0f (     SECT EXT) 01     0000   00000000000ae294 '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfcfA_'
[  6083] 000528ef 0f (     SECT EXT) 01     0000   00000000000ae324 '__T013ResourceQueueAACMa'
[  6084] 00052908 0f (     SECT EXT) 08     0000   0000000000104a84 '__T013ResourceQueueAACMn'
[  6085] 00052921 0f (     SECT EXT) 01     0000   00000000000aebd4 '__T013ResourceQueueAACfD'
[  6086] 0005293a 0f (     SECT EXT) 01     0000   00000000000aebbc '__T013ResourceQueueAACfd'
[  2737] 0002d7cc 1e (PEXT SECT    ) 01     0000   00000001000972c0 '__T013ResourceQueueAAC7recoveryyF'
[  2738] 0002d7ee 1e (PEXT SECT    ) 01     0080   0000000100097890 '__T013ResourceQueueAAC6removeyx2at_tFSbx_q_t_tcfU_'
[  2740] 0002d863 0e (     SECT    ) 01     0000   0000000100097ab0 '__T013ResourceQueueytWh2_'
[  2741] 0002d87d 0e (     SECT    ) 01     0000   0000000100097b40 '__T013ResourceQueueAAC6removeyx2at_tFSbx_q_t_tcfU_TA'
[  2743] 0002d8d5 0e (     SECT    ) 01     0000   0000000100097cc8 '__T013ResourceQueueytWh6_'
[  2746] 0002d99e 0e (     SECT    ) 01     0000   0000000100097e38 '__T013ResourceQueueAAC7dequeueq_Sgx2at_tFSbx_q_t_tcfU_TA'
[  3871] 0003a073 1e (PEXT SECT    ) 04     0000   00000001000d4308 '__T013ResourceQueueAAC5queueSayx_q_tGvpWvd'
[  3872] 0003a09e 1e (PEXT SECT    ) 04     0000   00000001000d4310 '__T013ResourceQueueAAC11queueLengthSivpWvd'
[  3982] 0003af9d 1e (PEXT SECT    ) 0b     0080   00000001000f87c0 '__T013ResourceQueueAACMF'
[  5116] 00046417 1e (PEXT SECT    ) 24     0080   0000000100138558 '__T013ResourceQueueAACySS7PromiseACCySo7UIImageCGGML'
[  5526] 0004cc37 1e (PEXT SECT    ) 24     0080   000000010013a2a0 '__T013ResourceQueueAACMP'
[  6017] 00051c08 0f (     SECT EXT) 01     0000   0000000100097a44 '__T013ResourceQueue07GenericA9CollectorCACyxq_q0_GSi6length_q_xcq0_xctcfcfA_'
[  6018] 00051c55 0f (     SECT EXT) 01     0000   0000000100097a3c '__T013ResourceQueue0A17CollectorStringedCACyxGSi6length_xSSctcfcfA_'
[  6019] 00051c99 0f (     SECT EXT) 01     0000   00000001000976c0 '__T013ResourceQueueAAC5cleanyyF'
[  6020] 00051cb9 0f (     SECT EXT) 01     0000   00000001000976fc '__T013ResourceQueueAAC6removeyx2at_tF'
[  6021] 00051cdf 0f (     SECT EXT) 01     0000   00000001000974dc '__T013ResourceQueueAAC7dequeueq_Sgx2at_tF'
[  6022] 00051d09 0f (     SECT EXT) 01     0000   0000000100097410 '__T013ResourceQueueAAC7enqueueyq_8resource_x3fortF'
[  6023] 00051d3c 0f (     SECT EXT) 01     0000   0000000100097408 '__T013ResourceQueueAAC9setLengthySiF'
[  6024] 00051d61 0f (     SECT EXT) 01     0000   00000001000971a8 '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfC'
[  6025] 00051d94 0f (     SECT EXT) 01     0000   0000000100097268 '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfc'
[  6026] 00051dc7 0f (     SECT EXT) 01     0000   00000001000971a0 '__T013ResourceQueueAACAByxq_GSi12withLengthOf_tcfcfA_'
[  6027] 00051dfd 0f (     SECT EXT) 01     0000   0000000100097238 '__T013ResourceQueueAACMa'
[  6028] 00051e16 0f (     SECT EXT) 04     0000   00000001000d4268 '__T013ResourceQueueAACMn'
[  6029] 00051e2f 0f (     SECT EXT) 01     0000   0000000100097a18 '__T013ResourceQueueAACfD'
[  6030] 00051e48 0f (     SECT EXT) 01     0000   00000001000979fc '__T013ResourceQueueAACfd'
```
Not seing any `N_` while `grep`ping

**Comment by isaac-weisberg** [comment]
`grep`ping `N_` also no relevant output. Relevant to `ResourceQueue` that is.

**Comment by isaac-weisberg** [comment]
@blender essentially, to summarize, it doesn't require any additional input from the developer apart from stuff written in the docs in the PR.
So what about the README, what info needs to be rewritten-updated?

**Comment by blender** [comment]
Instructions seem fine to me, that for all the work!

Since 0.30.0 is not out yet I think we should hold off merging till the last moment.

**Comment by isaac-weisberg** [comment]
Obviously! <3

**Comment by chronodm** [comment]
I'm new to Swift development so forgive me if I'm missing something obvious here, but it's still not clear to me from the new docs just how this works or what it does. The heading says

> [Build static frameworks to speed up your app’s launch times](https://github.com/Carthage/Carthage#build-static-frameworks-to-speed-up-your-apps-launch-times)

which seems to imply that if I have an app project that uses Carthage to pull in dependencies, I can somehow build these dependencies as static frameworks. But the instruction

> In your Carthage-compliant project's Cocoa Framework target's Build Settings, Linking section, set **Mach-O Type** to **Static Library**

—which is the only concrete instruction on how to enable this functionality—seems to imply that we're not talking about the app project at all, but about the projects for each framework. Which, ordinarily, I wouldn't even open in XCode, because I'm expecting Carthage to build them for me. Am I supposed to add an extra Cocoa Framework target, with Static Library Mach-O target, that pulls in all the libraries from the Cartfile, and then have the app target depend on that synthetic framework instead of directly on the Cartfile dependencies? Or am I barking up the wrong tree entirely and just failing to understand what this feature is for?

**Comment by blender** [comment]
The feature added in 0.30.1 is the ability for Carthage to build frameworks with `Mach-O Type` set to `Static Lib`.  This makes it possible for the user to now depend on Static Framework projects.

So for example, you can now package your __own__ frameworks as Static and have them linked that way into your app.

Changing the Mac-O Type of 3rd party frameworks and building proxy targets, is something that people have come up with to speed up their app launch times. That has nothing to do with Carthage. It's a byproduct of the feature.

**Pull request merged**
