### PR TITLE
Specify destination for simulator builds

### PR DESCRIPTION
**Pull request by ikesyo**
This seems to be required for Xcode 7.2.

https://github.com/Carthage/Carthage/issues/790#issuecomment-159349939 should be the case.

### CODE REVIEW

**Comment by NachoSoto** [comment]
😵😵😵

This might actually work around http://www.openradar.appspot.com/22993940!!

**Comment by NachoSoto** [comment]
Thus looks good! Awesome find @ikesyo, I didn't realize we had this implemented but only for iOS!

:shipit:

**Comment by mdiep** [comment]
:clap:

**Comment by NachoSoto** [comment]
Apple got back to me in [rdar://22993940](http://www.openradar.appspot.com/22993940):
> While we will investigate this behavioral change, we recommend using the `-destination` flag rather than the `-sdk` flag for this use case.

So looks like you got it right @ikesyo! Still they said they're going to look into it because they broke a previously working command...

**Pull request merged**
